// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARh7GuCGMjwub78qfHEQKeQeP8O0w0pAQ',
    appId: '1:356526237288:web:4605f713a19644c5ccbddd',
    messagingSenderId: '356526237288',
    projectId: 'learneventvision',
    authDomain: 'learneventvision.firebaseapp.com',
    storageBucket: 'learneventvision.appspot.com',
    measurementId: 'G-Z0891KC1VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd8HdfEQTmPzUfjY49_3WlEDNfqof5F4M',
    appId: '1:356526237288:android:89619e373ad21396ccbddd',
    messagingSenderId: '356526237288',
    projectId: 'learneventvision',
    storageBucket: 'learneventvision.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGHgYF80gYkUT_D2Icdhn7MYuPUM4lx1g',
    appId: '1:356526237288:ios:55bebe014adfb52dccbddd',
    messagingSenderId: '356526237288',
    projectId: 'learneventvision',
    storageBucket: 'learneventvision.appspot.com',
    iosClientId: '356526237288-dflj9urcmdabp9lst83gj1re15kjd107.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGHgYF80gYkUT_D2Icdhn7MYuPUM4lx1g',
    appId: '1:356526237288:ios:55bebe014adfb52dccbddd',
    messagingSenderId: '356526237288',
    projectId: 'learneventvision',
    storageBucket: 'learneventvision.appspot.com',
    iosClientId: '356526237288-dflj9urcmdabp9lst83gj1re15kjd107.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
